services:
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./apps/client:/app/apps/client
      - ./packages/shared:/app/packages/shared
      - /app/node_modules

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./apps/server:/app/apps/server
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
